name: ${project.name}
main: net.daboross.bukkitdev.skychat.SkyChatPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
url: ${project.url}
commands:
  skychatreload:
    permission: skychat.reload
    usage: /<command>